# Generated by Django 2.1.7 on 2019-05-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movies_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('rating', models.FloatField(blank=True, default=None, null=True)),
                ('year', models.IntegerField(blank=True, default=None, null=True)),
                ('cast', models.ManyToManyField(to='movies.Cast_List')),
            ],
        ),
    ]
